#!/usr/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let request = require('request');
let url = process.argv[2];

if (!url) {
	console.log("Usage: wikp <url>");
	process.exit();
}

const jsdom = require('jsdom');
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
	let { document } = (new JSDOM(body)).window;

	//Grab all the paragraphs and references
	let paragraphs = document.querySelectorAll("p");
	let references = document.querySelectorAll(".reference");

	//Remove any references
	references.forEach(function(reference) {
		reference.remove();
	});

	//Print out all the paragraphs
	paragraphs.forEach(function(paragraph) {
		console.log(paragraph.textContent);
	});
});
